<?php
namespace App\Langs;

use WebFiori\Framework\Lang;

class LangEN extends Lang {
    public function __construct() {
        parent::__construct('ltr', 'EN');
        $this->createAndSet('nav', [
            'dashboard' => 'Dashboard', 'projects' => 'Projects', 'reports' => 'Reports',
            'users' => 'Users', 'audit-log' => 'Audit Log', 'settings' => 'Settings',
            'login' => 'Login', 'logout' => 'Logout',
        ]);
        $this->createAndSet('common', [
            'name' => 'Name', 'email' => 'Email', 'role' => 'Role', 'status' => 'Status',
            'actions' => 'Actions', 'save' => 'Save', 'delete' => 'Delete', 'edit' => 'Edit',
            'create' => 'Create', 'submit' => 'Submit', 'search' => 'Search',
            'password' => 'Password', 'login-title' => 'Dashboard Login',
            'welcome' => 'Welcome', 'active' => 'Active', 'id' => 'ID',
            'description' => 'Description', 'owner' => 'Owner', 'created' => 'Created',
            'title' => 'Title', 'generated-by' => 'Generated By',
            'user' => 'User', 'action' => 'Action', 'entity' => 'Entity',
            'ip' => 'IP', 'date' => 'Date', 'yes' => 'Yes', 'no' => 'No',
            'theme' => 'Theme', 'language' => 'Language', 'light' => 'Light', 'dark' => 'Dark',
            'current-theme' => 'Current theme', 'not-found' => 'Not found',
            'manage-users' => 'Manage Users', 'project-detail' => 'Project Detail',
        ]);
    }
}
